# Generated by Django 4.0.1 on 2022-01-04 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(2099), django.core.validators.MinValueValidator(2021)])),
                ('month', models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
