# Generated by Django 4.0.1 on 2022-01-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0002_alter_month_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakturownia_id', models.IntegerField()),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=12)),
                ('order_id', models.CharField(max_length=8)),
                ('buyer', models.CharField(max_length=32)),
                ('warehouse_id', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.month')),
            ],
        ),
    ]
