# Generated by Django 4.0.1 on 2022-01-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('fakturownia_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fakturownia_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='InvoicePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.product')),
            ],
        ),
    ]
