# Generated by Django 4.0.1 on 2022-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0005_alter_invoice_fakturownia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fakturownia_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fakturownia_id',
            field=models.IntegerField(unique=True),
        ),
    ]
