# Generated by Django 4.0.1 on 2022-01-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0006_alter_invoice_fakturownia_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=8)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.month')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.product')),
                ('production_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.productiondoc')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='production_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produkcja.productionposition'),
        ),
    ]
