# Generated by Django 4.0.1 on 2022-01-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0008_remove_productionposition_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceposition',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
