# Generated by Django 4.0.1 on 2022-01-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0009_invoiceposition_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakturownia_id', models.IntegerField(unique=True)),
                ('number', models.CharField(max_length=10)),
                ('issue_date', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=128)),
                ('odoo_id', models.IntegerField(null=True, unique=True)),
                ('production_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produkcja.productiondoc')),
            ],
        ),
    ]
