# Generated by Django 4.0.1 on 2022-01-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0010_rw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rw',
            name='production_doc',
        ),
        migrations.AddField(
            model_name='productiondoc',
            name='rw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produkcja.rw'),
        ),
        migrations.AddField(
            model_name='rw',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produkcja.month'),
        ),
    ]
