# Generated by Django 4.0.1 on 2022-01-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0011_remove_rw_production_doc_productiondoc_rw_rw_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionposition',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
