# Generated by Django 4.0.1 on 2022-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0012_productionposition_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondoc',
            name='odoo_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
