# Generated by Django 4.0.1 on 2022-01-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0013_productiondoc_odoo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondoc',
            name='do_not_produce',
            field=models.BooleanField(default=False),
        ),
    ]
