# Generated by Django 4.0.1 on 2022-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0014_productiondoc_do_not_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondoc',
            name='number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='productiondoc',
            name='rw_date',
            field=models.DateField(null=True),
        ),
    ]
