# Generated by Django 4.0.1 on 2022-01-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0016_productiondoc_order_name_alter_rw_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondoc',
            name='rw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produkcja.rw'),
        ),
    ]
