# Generated by Django 4.0.1 on 2022-01-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0017_alter_productiondoc_rw'),
    ]

    operations = [
        migrations.AddField(
            model_name='rw',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
