# Generated by Django 4.0.1 on 2022-01-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0018_rw_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionposition',
            name='do_not_produce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionposition',
            name='raw_materials_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='productionposition',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
